[package]
name = "custom-verkle"
version = "0.1.0"
edition = "2021"

[dependencies]
curve25519-dalek = { version = "4.1.3", features = ["rand_core", "digest"] }
hex = "0.4.3"
rand = "0.8.0"
sha2 = "0.10.8"
